name = "Coordinates"
uuid = "e9ef043c-5f73-4baa-bfac-7a9763f7755c"
authors = ["Abhro R. and contributors"]
version = "0.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DocStringExtensions = "0.9"
LinearAlgebra = "1"
julia = "1.10"
